// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bC4ttRe1b8bW9HyK9nUO6zWTkKh3LsM',
    appId: '1:619795656218:web:010c054f895b1830742ba3',
    messagingSenderId: '619795656218',
    projectId: 'fbauthen-d7a8c',
    authDomain: 'fbauthen-d7a8c.firebaseapp.com',
    storageBucket: 'fbauthen-d7a8c.firebasestorage.app',
    measurementId: 'G-JPY4VFHP2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrIK6Slc9qv6LOXdMyepuCDodI3AzInIA',
    appId: '1:619795656218:android:e632f7bb7e43705f742ba3',
    messagingSenderId: '619795656218',
    projectId: 'fbauthen-d7a8c',
    storageBucket: 'fbauthen-d7a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVr3_bNIr-YmUrH8him2TFFjLRqF2cvxo',
    appId: '1:619795656218:ios:7259f70971aaec94742ba3',
    messagingSenderId: '619795656218',
    projectId: 'fbauthen-d7a8c',
    storageBucket: 'fbauthen-d7a8c.firebasestorage.app',
    iosBundleId: 'com.example.fbAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVr3_bNIr-YmUrH8him2TFFjLRqF2cvxo',
    appId: '1:619795656218:ios:7259f70971aaec94742ba3',
    messagingSenderId: '619795656218',
    projectId: 'fbauthen-d7a8c',
    storageBucket: 'fbauthen-d7a8c.firebasestorage.app',
    iosBundleId: 'com.example.fbAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1bC4ttRe1b8bW9HyK9nUO6zWTkKh3LsM',
    appId: '1:619795656218:web:4787e7d9cba85eb7742ba3',
    messagingSenderId: '619795656218',
    projectId: 'fbauthen-d7a8c',
    authDomain: 'fbauthen-d7a8c.firebaseapp.com',
    storageBucket: 'fbauthen-d7a8c.firebasestorage.app',
    measurementId: 'G-C6GN2YBJTV',
  );

}